ARG BASE_IMAGE=nvidia/cuda:10.1-cudnn7-devel-ubuntu18.04
ARG PYTHON_VERSION=3.6

FROM ${BASE_IMAGE} as dev-base
RUN apt-get update && apt-get install -y --no-install-recommends \
        build-essential \
        ca-certificates \
        ccache \
        cmake \
        curl \
        git \
        ca-certificates \
        openssh-client \
        libjpeg-dev \
        libpng-dev &&\
    rm -rf /var/lib/apt/lists/*
RUN /usr/sbin/update-ccache-symlinks
RUN mkdir /opt/ccache && ccache --set-config=cache_dir=/opt/ccache
ENV PATH /opt/conda/bin:$PATH

FROM dev-base as openmpi
RUN curl -L -O https://www.open-mpi.org/software/ompi/v3.1/downloads/openmpi-3.1.6.tar.gz && \
    gunzip -c openmpi-3.1.6.tar.gz | tar xf - && \
    cd openmpi-3.1.6 && \
    ./configure --prefix=/home/.openmpi --with-cuda && \
    make all install
ENV PATH="$PATH:/home/.openmpi/bin"
ENV LD_LIBRARY_PATH="${LD_LIBRARY_PATH}:/home/.openmpi/lib/"
RUN ompi_info --parsable --all | grep mpi_built_with_cuda_support:value

FROM openmpi as conda
RUN curl -L -o ~/miniconda.sh -O https://repo.continuum.io/miniconda/Miniconda3-latest-Linux-x86_64.sh  && \
    chmod +x ~/miniconda.sh && \
    ~/miniconda.sh -b -p /opt/conda && \
    rm ~/miniconda.sh && \
    /opt/conda/bin/conda install -y python=${PYTHON_VERSION} conda-build pyyaml numpy ipython scipy mkl mkl-include cython typing && \
    /opt/conda/bin/conda clean -ya
ENV PATH=/opt/conda/bin:$PATH

FROM conda as build
WORKDIR /opt/pytorch
RUN git clone --recursive https://github.com/pytorch/pytorch
RUN cd pytorch && \
    TORCH_CUDA_ARCH_LIST="3.5 5.2 6.0 6.1 7.0+PTX" TORCH_NVCC_FLAGS="-Xfatbin -compress-all" \
    CMAKE_PREFIX_PATH="$(dirname $(which conda))/../" \
    python setup.py install

RUN git clone https://github.com/pytorch/vision.git
RUN cd vision && \
    python setup.py install

RUN pip install pillow tensorboardX

WORKDIR /app
COPY mnist.py /app

ENTRYPOINT ["mpirun", "-n", "1", "--allow-run-as-root", "python", "/app/mnist.py"]