apiVersion: "kubeflow.org/v1"
kind: "PyTorchJob"
metadata:
  name: "training-gloo-pytorchjob"
spec:
  pytorchReplicaSpecs:
    Master:
      replicas: 1
      restartPolicy: OnFailure
      template:
        metadata:
          annotations:
            sidecar.istio.io/inject: "false"
        spec:
          containers:
            - name: pytorch
              image: kangwoo/training-pytorchjob:0.0.1
              args: ["--backend", "gloo"]
#              resources:
#                limits:
#                  nvidia.com/gpu: 1
    Worker:
      replicas: 1
      restartPolicy: OnFailure
      template:
        metadata:
          annotations:
            sidecar.istio.io/inject: "false"
        spec:
          containers:
            - name: pytorch
              image: kangwoo/training-pytorchjob:0.0.1
              args: ["--backend", "gloo"]
#              resources:
#                limits:
#                  nvidia.com/gpu: 1