apiVersion: batch/v1
kind: Job
metadata:
  name: training-fashion-mnist-gpu-job
spec:
  template:
    metadata:
      name: training-fashion-mnist-gpu-job
      annotations:
        sidecar.istio.io/inject: "false"
    spec:
      containers:
        - command:
            - python
            - /app/tensorflow_fashion_mnist.py
          image: kangwoo/training-fashion-mnist-gpu-job:0.0.1
          imagePullPolicy: IfNotPresent
          name: job
          resources:
            limits:
              nvidia.com/gpu: 1
      restartPolicy: Never
