apiVersion: "serving.kubeflow.org/v1alpha2"
kind: "InferenceService"
metadata:
  name: "mnist-s3"
spec:
  default:
    predictor:
      serviceAccountName: s3-sa
      tensorflow:
        storageUri: "s3://tensorflow/fashion-mnist/model"